name: example
publish_to: none
version: 0.0.1
homepage: https://pwa.ir
repository: https://github.com/xclud/web3dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies: 
  web3dart:
    path: ../
  # code generation for contracts, shouldn't be imported outside of lib/src/builder/
  build: ^2.0.0
  build_config: ^1.0.0
  code_builder: ^4.0.0
  path: ^1.8.0

  built_collection: ^5.0.0
  pointycastle: ^3.4.0
  convert: ^3.0.0
  meta: ^1.1.0
  http: ^0.13.0
  js: ^0.6.3
  uuid: ^3.0.1
  typed_data: ^1.1.6
  stream_channel: ^2.0.0
  stream_transform: ^2.0.0
  json_rpc_2: ^3.0.0
  collection: ^1.14.11

dev_dependencies:
  async: ^2.8.2
  build_runner: ^2.0.3
  build_test: ^2.1.0

  test: ^1.9.0
  coverage: ^1.1.0
  lints: ^1.0.0
