name: web3dart
description: Dart library to connect to Ethereum clients. Send transactions and interact with smart contracts!
version: 2.4.1
homepage: https://pwa.ir
repository: https://github.com/xclud/web3dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  pointycastle: ^3.6.0
  http: ^0.13.4
  uuid: ^3.0.6
  json_rpc_2: ^3.0.2
  stream_transform: ^2.0.0
  stream_channel: ^2.1.0
  eip55: ^1.0.2
  collection: ^1.16.0
  typed_data: ^1.3.1
  convert: ^3.0.2
  async: ^2.9.0

dev_dependencies:
  test: ^1.21.3
  lints: ^2.0.0
